### ISSUE TITLE
Arctos: Identifications

### ISSUE THREAD

**Issue by Jegelewicz** [gbif/model-material#117] opened 2023-03-22 21:17 UTC
From https://github.com/ArctosDB/internal/issues/249

    Shouldn't all of the parts inherit identifications from the organism record? Maybe we need some tweaking there?

@tucotuco says
>Not in GUM, no. Identifications are associated directly to Organisms. I think the UI is the problem here, not the data. Can you make an issue for this as well. It's an important problem of the UI.

**Comment by tucotuco** [comment] 2023-03-23 00:46
@MortenHofft  To me the specific problem is having a separate page (example, https://arctos.database.museum/guid/MSB:Host:15217/PID22723022) for the part. Do we have any examples of where that is a useful additional page? I imagine there is no taxon in the page banner because Organisms are the things that are Identified. That would always be a problem with parts pages.

**Comment by MortenHofft** [comment] 2023-03-23 09:33
It might not, but...

I *think* it makes sense, simply because there is nothing in the model that prevents a part from having a TON of data. Assertions, identifications, unique agents working on it. Belong to a different collection, have its own catalogue number etc. For all I know it could be far richer in data than the material it is a part of. And could have its own parts, own media.

So unless there is agreement what the relation type "PART OF" means - then I kind have to assume that anything could happen.
So for now I opted to show a few fields that I figured was relevant (preservation, disposition), and then link to it for further details (if there is any). What that summary ought to be I'm not sure. And perhaps there could be a way to detect if a separate page makes sense.

But it would be nice to
* Know what to expect from parts
* And secondly label the page more clearly as being a "part" page.

The Koldingensis example has 3 entities: 
Tissue that is `MATERIAL SAMPLE OF` the dried specimen that is `MATERIAL SAMPLE OF` the organism.

Either way, it makes sense to inherit the identification if none is provided on the part.

**Comment by MortenHofft** [comment] 2023-03-23 14:43
> That isn't incorrect. But I'll be curious to see what happens with a paleo specimen with a multitude of organisms in it, or the Arctos parka example (i.e., a material entity with multiple organisms with one or more identifications).

I have no doubt it will cause headaches

**Comment by dustymc** [comment] 2023-03-23 15:52
>part from having a TON of data.

Yes, but it's normalized. We don't eg identify each of the 500 parts, we identify the catalog record (Organism-ish, sometimes) and that propagates down to each of the parts. (And of course parts are sometimes used to make those identifications and etc., but that's probably safe to ignore for now.)

>Assertions

Yes, each with agents and methods and such (in table assertion).

>unique agents

Yep, each assertion (can) involve an Agent.

>Belong to a different collection

Not for Arctos. (That's not to say two collections haven't cataloged the same group of atoms, but it will appear as two parts - and a relationship, we hope - with "collection" as a parent of the parent of parts.

>have its own catalogue number etc.

No, but probably just because we think that means something weird. One type of "assertion" is part identifier [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecpart_attribute_type#part_identifier) which might involve things that some would call catalog numbers. Any part can have any number of them, and they can be "1" or guids or whatever.

>far richer in data than the material it is a part of. 

Sorta, because normalization. The child necessarily carries more data than the parent can because it carries all of the parent and SOMETHING of its own (it has to to exist).

> have its own parts,

Yes. (I'm not sure we're sharing that, but Arctos parts are in a hierarchy of indeterminate depth. Starting with a moose liver, we can theoretically go through hundreds of subsampling events.)

>own media

Yes. (We have none, but it would be a simple code table request to add to Arctos.)

>what the relation type "PART OF" 

That's easy (ha!). Catalog items are conceptual "whatever someone felt like cataloging." They represent individuals (and motorcycles and the share of an individual in this collection and Occurrences - not that we'd be able to tell - and.....) Parts are physical things - "things to which one might stick a barcode." They are children of cataloged items. They include pickled snakes and liver subsamples (and bus fenders and glass slides and that skull nobody's been able to find since 1871 and resin reproductions printed from CT scans of casts of parts and .....)

So, easy. There's only one "primary" relationship between catalog items and parts, and it's also the separation between conceptual and physical. (Or maybe impossibly complicated, depending on your perspective...)

>way to detect if a separate page makes sense.

I think it never will for Arctos - parts are meaningless out of the context of their catalog records, and possibly the context of their sister parts. (That's not to say that some sort of summary/detail view or whatever would be bad, just that parts can't survive being entirely isolated from their parents.)

**Comment by tucotuco** [comment] 2023-03-31 17:33
Does this issue require any further action @MortenHofft @Jegelewicz ?

**Comment by MortenHofft** [comment] 2023-04-03 09:41
I think we can close this issue in favour of https://github.com/gbif/model-material/issues/129 and https://github.com/gbif/model-material/issues/130

**Closed by MortenHofft** 2023-04-03 09:41 UTC
